### ISSUE TITLE
Bug Strings Import

### ISSUE THREAD

**Issue by Jetrom17** [sunilpaulmathew/Translator#36]
Application closes itself after importing any string. This happens on my Android 11. 

![Screenshot_20221104-091717.png](https://user-images.githubusercontent.com/72875404/199971172-12404cfe-ee69-4e8e-acdf-944732dd9aa3.png)

**Comment by sunilpaulmathew** [comment]
@Jeiel17 
I just tried it on two emulators (Android 11 and 13). Both worked without any issue. I really don't know what happened in your case. Probably, a crash log helps.

**Comment by Jeiel17** [comment]
> @Jeiel17 
> I just tried it on two emulators (Android 11 and 13). Both worked without any issue. I really don't know what happened in your case. Probably, a crash log helps.

How many Strings does the application support in KB?

**Comment by sunilpaulmathew** [comment]
Difficult to tell, but it depends on the available memory.

**Comment by Jeiel17** [comment]
> Difficult to tell, but it depends on the available memory.

[String](https://we.tl/t-ACliFF0mSw) Try running this file on your . This is what the application is not able to translate. In fact, it's the app's fault.

**Comment by sunilpaulmathew** [comment]
> > Difficult to tell, but it depends on the available memory.
> 
> [String](https://we.tl/t-ACliFF0mSw) Try running this file on your . This is what the application is not able to translate. In fact, it's the app's fault.

Thanks. I found the issue. Will try to fix in future.
