### ISSUE TITLE
How can i help with translation?

### ISSUE THREAD

**Issue by jakubfabijan** [sunilpaulmathew/Translator#9]
I want to translate this app to Esperanto, but i don't know how to submit it to you when i done.

**Comment by sunilpaulmathew** [comment]
Hi,
Thanks a lot for your interest.
You can either create a pull request (if you are comfortable with GitHub related things) or personally send file to me (either link here, or via our telegram chat: link available in app). Either way, I'll take care of the rest.

**Comment by jakubfabijan** [comment]
Done! [https://filebin.net/0d1v3ke96kknco15/strings.xml](link)

**Comment by jakubfabijan** [comment]
Done! [strings.xml](https://filebin.net/0d1v3ke96kknco15/strings.xml)

**Comment by sunilpaulmathew** [comment]
> Done! [strings.xml](https://filebin.net/0d1v3ke96kknco15/strings.xml)

@jakubfabijan 
Thanks a lot for your work. May I ask you to test [this](https://www.dropbox.com/s/bh55fme9avutlwt/com.sunilpaulmathew.translator.apk?dl=0) APK. Just to make sure that everything is fine before I release it to public.

**Comment by jakubfabijan** [comment]
![Screenshot_20210131-122512](https://user-images.githubusercontent.com/53099243/106382605-f332de80-63c0-11eb-9966-9a030bdac272.png)
![Screenshot_20210131-123457](https://user-images.githubusercontent.com/53099243/106382606-f4640b80-63c0-11eb-9fec-ec30f34d1e13.png)
Yes, works good.

**Comment by sunilpaulmathew** [comment]
@jakubfabijan Cool. Do you have an email address associated with this account? If so, I'll provide you with the authorship of your contribution.

**Comment by jakubfabijan** [comment]
You don't really have to, but if you really want "animatorzpolski@gmail.com".
